#define FLOW_TAP_TERM 80
#define CHORDAL_HOLD
#undef DEBOUNCE
#define DEBOUNCE 3

#undef TAPPING_TERM
#define TAPPING_TERM 135
#define QUICK_TAP_TERM 100

#define ONESHOT_TAP_TOGGLE 2

#undef ONESHOT_TIMEOUT
#define ONESHOT_TIMEOUT 1

#define PERMISSIVE_HOLD
#define ACHORDION_STREAK
#define ACHORDION_CHORD_TIMEOUT 240

#undef RGB_MATRIX_TIMEOUT
#define RGB_MATRIX_TIMEOUT 600000

#define USB_SUSPEND_WAKEUP_DELAY 0
#define CAPS_LOCK_STATUS
#define SERIAL_NUMBER "rd7Ab/jZDB5w"
#define LAYER_STATE_8BIT
#define COMBO_COUNT 1

#define TAPPING_TERM_PER_KEY
#define RGB_MATRIX_STARTUP_SPD 60

