#define FLOW_TAP_TERM 47
#define CHORDAL_HOLD
#undef DEBOUNCE
#define DEBOUNCE 3

#undef TAPPING_TERM
#define TAPPING_TERM 250

#define RETRO_TAPPING

#define ONESHOT_TAP_TOGGLE 2

#undef ONESHOT_TIMEOUT
#define ONESHOT_TIMEOUT 1

#define PERMISSIVE_HOLD

#undef RGB_MATRIX_TIMEOUT
#define RGB_MATRIX_TIMEOUT 600000

#define USB_SUSPEND_WAKEUP_DELAY 0
#define CAPS_LOCK_STATUS
#define SERIAL_NUMBER "rd7Ab/WvG303"
#define LAYER_STATE_8BIT
#define COMBO_COUNT 1

#define TAPPING_TERM_PER_KEY
#define RGB_MATRIX_STARTUP_SPD 60

