name: Build Firmware
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Compile Voyager
        run: make zsa/voyager:the-home-row-mods
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: .build/obj_zsa_voyager_the-home-row-mods/
